# docker-compose.yml
version: "3.8"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - proxynet
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # --- THESE TWO LINES ARE THE CRUCIAL CORRECTION ---
    entrypoint: ["/bin/bash", "-c"] # Override the image's default entrypoint with a shell that runs a command string
    command: > # This entire block is now the command string passed to /bin/bash -c
      "
      /bin/ollama serve &
      OLLAMA_PID=$!
      echo 'Waiting for Ollama server to start...'
      sleep 10
      echo 'Downloading Ollama models...'
      ollama pull llama3
      ollama pull llama3-groq-tool-use
      echo 'Model download complete.'
      wait $OLLAMA_PID
      "
    # --- END CORRECTION ---

  fastapi:
    image: "fastapi:latest"
    build:
        context: ./fastapi
        dockerfile: ./docker/Dockerfile
    restart: always
    container_name: fastapi
    networks:
      - proxynet
    ports:
        - 8000:8000
    expose:
        - 8000

volumes:
  ollama_data:

networks:
  proxynet:
    name: smart_network