# docker-compose.yml (Final Attempt - Direct shell execution of script)
version: "3.8"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - proxynet
    volumes:
      # Keep the mount as it is, it's working correctly now
      - ${PWD}/entrypoint.sh:/usr/local/bin/ollama-startup.sh 
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # --- CRITICAL CHANGE: Only the script path as the command to /bin/sh ---
    # The container's effective command will be: /bin/sh -c "/usr/local/bin/ollama-startup.sh"
    # This tells /bin/sh to read and execute the content of that file.
    entrypoint: ["/bin/sh"] # Execute /bin/sh directly
    command: ["-c", "/usr/local/bin/ollama-startup.sh"] # Pass the script's path as the command string to -c

  fastapi:
    image: "fastapi:latest"
    build:
        context: ./fastapi
        dockerfile: ./docker/Dockerfile
    restart: always
    container_name: fastapi
    networks:
      - proxynet
    ports:
        - 8002:8002
    expose:
        - 8002

volumes:
  ollama_data:

networks:
  proxynet:
    name: smart_network