# docker-compose.yml
version: "3.8"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - proxynet
    volumes:
      - ollama_data:/root/.ollama # Keep your data volume
    ports:
      - "11434:11434"
    # No custom entrypoint or command needed here.
    # The image's default entrypoint will start the ollama server.

  fastapi:
    image: "fastapi:latest"
    build:
        context: ./fastapi
        dockerfile: ./docker/Dockerfile
    restart: always
    container_name: fastapi
    networks:
      - proxynet
    ports:
        - 8003:8003
    expose:
        - 8003

volumes:
  ollama_data:

networks:
  proxynet:
    name: smart_network