# docker-compose.yml (New Attempt - Explicit Arguments)
version: "3.8"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - proxynet
    volumes:
      # Keep the new path for the mounted script, confirmed to be a file
      - ${PWD}/entrypoint.sh:/usr/local/bin/ollama-startup.sh 
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # --- CRITICAL CHANGE: entrypoint and command as lists ---
    # The container's effective command will be: /bin/sh -c "chmod +x /path && /path"
    entrypoint: ["/bin/sh"] # Execute /bin/sh directly
    command: ["-c", "chmod +x /usr/local/bin/ollama-startup.sh && /usr/local/bin/ollama-startup.sh"]

  fastapi:
    image: "fastapi:latest"
    build:
        context: ./fastapi
        dockerfile: ./docker/Dockerfile
    restart: always
    container_name: fastapi
    networks:
      - proxynet
    ports:
        - 8002:8002
    expose:
        - 8002

volumes:
  ollama_data:

networks:
  proxynet:
    name: smart_network