# docker-compose.yml
version: "3.8"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - proxynet
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    entrypoint: [] # <<< CORRECTED: This clears the default entrypoint of the ollama image
    command: ["tail", "-f", "/dev/null"] # <<< This will now be the main command executed

  fastapi:
    image: "fastapi:latest"
    build:
        context: ./fastapi
        dockerfile: ./docker/Dockerfile
    restart: always
    container_name: fastapi
    networks:
      - proxynet
    ports:
        - 8000:8000
    expose:
        - 8000

volumes:
  ollama_data:

networks:
  proxynet:
    name: smart_network