# docker-compose.yml
version: "3.8"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - proxynet
    volumes:
      # --- CRITICAL CHANGE FOR THE MOUNT ---
      # Explicitly use the current directory variable on the host for the source path.
      # Mount it to a new, distinct location and name in the container (e.g., /usr/local/bin/ollama-startup.sh)
      # On Linux/macOS, ${PWD} works. On Windows, Docker Desktop often handles `./` correctly,
      # but if not, you might need to use an absolute path like C:/path/to/your/project/entrypoint.sh
      - ${PWD}/entrypoint.sh:/usr/local/bin/ollama-startup.sh 
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # --- Execute the mounted script via a shell ---
    entrypoint: ["/bin/sh", "-c"] 
    command: "chmod +x /usr/local/bin/ollama-startup.sh && /usr/local/bin/ollama-startup.sh"

  fastapi:
    image: "fastapi:latest"
    build:
        context: ./fastapi
        dockerfile: ./docker/Dockerfile
    restart: always
    container_name: fastapi
    networks:
      - proxynet
    ports:
        - 8002:8002
    expose:
        - 8002

volumes:
  ollama_data:

networks:
  proxynet:
    name: smart_network