# docker-compose.yml
version: "3.8"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - proxynet
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh # Mount your custom entrypoint script
    ports:
      - "11434:11434"
    entrypoint: ["/entrypoint.sh"] # Use your custom entrypoint script

  fastapi:
    image: "fastapi:latest"
    build:
        context: ./fastapi
        dockerfile: ./docker/Dockerfile
    restart: always
    container_name: fastapi
    networks:
      - proxynet
    ports:
        - 8002:8002
    expose:
        - 8002

volumes:
  ollama_data:

networks:
  proxynet:
    name: smart_network