# app.py

from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field
from typing import Optional, Any, List, Tuple
import asyncio

# IMPORTANT CHANGE: Import the correct initialization function from your agent.py file
from agent import initialize_hierarchical_agent # Changed from initialize_openapi_agent

# Global variables to hold the initialized agent, token, and persona
openapi_agent_instance = None # Renamed for clarity, it's now the main hierarchical agent
global_access_token = None
global_teslabot_persona = "" # New global variable for the persona string

# Pydantic models for API request and response bodies
class AgentQueryRequest(BaseModel):
    message: str = Field(..., example="List all tasks.", description="The natural language query to send to the hierarchical agent.")

class IntermediateStep(BaseModel):
    action: str = Field(..., description="The action taken by the agent.")
    observation: str = Field(..., description="The observation received after the action.")

class AgentResponse(BaseModel):
    response: str = Field(..., example="Successfully retrieved 5 tasks: Task A, Task B, Task C, Task D, Task E.", description="The final response generated by the hierarchical agent.")
    intermediate_steps: Optional[List[IntermediateStep]] = Field(None, description="The thought process and intermediate steps of the agent.")

class HealthCheckResponse(BaseModel):
    status: str = Field(..., example="ok", description="Status of the API service.")
    agent_initialized: bool = Field(..., example=True, description="Indicates if the hierarchical agent has been successfully initialized.")

class ErrorResponse(BaseModel):
    detail: str = Field(..., example="Agent not initialized. Please try again later.", description="Error message providing details about the issue.")


# FastAPI app instance
app = FastAPI(
    title="Humanoid robot emulation API",
    description="An API to interact with a hierarchical LangChain agent emulating a humanoid robot capable of using the CrowdDrop API and other general tools.",
    version="1.0.0",
)

@app.on_event("startup")
async def startup_event():
    """
    Initializes the hierarchical agent by calling the function from agent.py
    when the FastAPI application starts up.
    """
    global openapi_agent_instance
    global global_access_token
    global global_teslabot_persona # Access the new global variable

    print("FastAPI app starting up: Initializing hierarchical agent...")
    # Unpack all three returned values from initialize_hierarchical_agent
    agent, token, persona = await initialize_hierarchical_agent() # Changed function call
    if agent:
        openapi_agent_instance = agent
        global_access_token = token
        global_teslabot_persona = persona # Store the persona
        print("Hierarchical agent successfully loaded into FastAPI app with persona.")
    else:
        print("Failed to initialize agent during startup.")

@app.post(
    "/chat",
    response_model=AgentResponse,
    status_code=status.HTTP_200_OK,
    summary="Send a chat message to the agent",
    description="Sends a natural language chat message to the underlying LangChain hierarchical agent, which can interact with the CrowdDrop API or answer general questions.",
    responses={
        status.HTTP_503_SERVICE_UNAVAILABLE: {"model": ErrorResponse, "description": "Agent not initialized"},
        status.HTTP_500_INTERNAL_SERVER_ERROR: {"model": ErrorResponse, "description": "Internal server error during agent processing"},
    },
    tags=["Agent"]
)
async def chat(request_body: AgentQueryRequest) -> AgentResponse:
    """
    Processes a user query using the initialized hierarchical agent.
    Includes the Teslabot persona in the query (via system message in agent setup)
    and returns intermediate steps.
    """
    if openapi_agent_instance is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Agent not initialized. Please try again later. Check server logs for initialization errors."
        )

    if global_access_token is None:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Authentication token not available. Agent cannot make authorized API calls. Check server logs for authentication errors."
        )
    
    # REMOVED: No longer prepending persona here. The persona is now part of the agent's
    # system message, so the agent is inherently aware of its persona.
    # user_query_with_persona = f"{global_teslabot_persona} {request_body.message}"
    # print(f"Received query (with persona): {user_query_with_persona}")

    print(f"Received query: {request_body.message}") # Log the original message

    try:
        # Pass the original message directly to the agent.
        # The agent's system message already contains the persona.
        response = await openapi_agent_instance.ainvoke(
            {"input": request_body.message}, # Pass the original user message
            return_intermediate_steps=True # Request intermediate steps
        )

        output_content = response.get("output", "No direct output from agent. Check agent's verbose output in server logs for details.")
        
        intermediate_steps_output: List[IntermediateStep] = []
        if 'intermediate_steps' in response and response['intermediate_steps']:
            for step in response['intermediate_steps']:
                action = str(step[0]) # Convert AgentAction object to string
                observation = str(step[1]) # Convert observation to string
                intermediate_steps_output.append(IntermediateStep(action=action, observation=observation))

        return AgentResponse(response=output_content, intermediate_steps=intermediate_steps_output)
    except Exception as e:
        print(f"Error invoking agent: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing request with agent: {str(e)}"
        )

@app.get(
    "/health",
    response_model=HealthCheckResponse,
    summary="Health check endpoint",
    description="Checks the health and initialization status of the API server and the hierarchical agent.",
    tags=["Monitoring"]
)
async def health_check() -> HealthCheckResponse:
    """
    Provides a simple health check to indicate if the API is running
    and if the core hierarchical agent has been successfully initialized.
    """
    return HealthCheckResponse(status="ok", agent_initialized=openapi_agent_instance is not None)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8003)